// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.ScratchMsgs.allLocales');

goog.require('Blockly.ScratchMsgs');


Blockly.ScratchMsgs.locales["en"] =
{
    "CONTROL_FOREVER": "forever",
    "CONTROL_REPEAT": "repeat %1",
    "CONTROL_IF": "if %1 then",
    "CONTROL_ELSE": "else",
    "CONTROL_STOP": "stop",
    "CONTROL_STOP_ALL": "all",
    "CONTROL_STOP_THIS": "this script",
    "CONTROL_STOP_OTHER": "other scripts in sprite",
    "CONTROL_WAIT": "wait %1 seconds",
    "CONTROL_WAITUNTIL": "wait until %1",
    "CONTROL_REPEATUNTIL": "repeat until %1",
    "CONTROL_WHILE": "while %1",
    "CONTROL_FOREACH": "for each %1 in %2",
    "CONTROL_STARTASCLONE": "when I start as a clone",
    "CONTROL_CREATECLONEOF": "create clone of %1",
    "CONTROL_CREATECLONEOF_MYSELF": "myself",
    "CONTROL_DELETETHISCLONE": "delete this clone",
    "CONTROL_COUNTER": "counter",
    "CONTROL_INCRCOUNTER": "increment counter",
    "CONTROL_CLEARCOUNTER": "clear counter",
    "CONTROL_ALLATONCE": "all at once",
    "DATA_SETVARIABLETO": "set %1 to %2",
    "DATA_CHANGEVARIABLEBY": "change %1 by %2",
    "DATA_SHOWVARIABLE": "show variable %1",
    "DATA_HIDEVARIABLE": "hide variable %1",
    "DATA_ADDTOLIST": "add %1 to %2",
    "DATA_DELETEOFLIST": "delete %1 of %2",
    "DATA_DELETEALLOFLIST": "delete all of %1",
    "DATA_INSERTATLIST": "insert %1 at %2 of %3",
    "DATA_REPLACEITEMOFLIST": "replace item %1 of %2 with %3",
    "DATA_ITEMOFLIST": "item %1 of %2",
    "DATA_ITEMNUMOFLIST": "item # of %1 in %2",
    "DATA_LENGTHOFLIST": "length of %1",
    "DATA_LISTCONTAINSITEM": "%1 contains %2?",
    "DATA_SHOWLIST": "show list %1",
    "DATA_HIDELIST": "hide list %1",
    "DATA_INDEX_ALL": "all",
    "DATA_INDEX_LAST": "last",
    "DATA_INDEX_RANDOM": "random",
    "EVENT_WHENARDUINOBEGIN": "when Arduino begin",
    "EVENT_WHENMICROBITBEGIN": "when Microbit begin",
    "EVENT_WHENMICROBITBUTTONPRESSED": "when button %1 pressed",
    "EVENT_WHENMICROBITPINBEINGTOUCHED": "when pin %1 being touched",
    "EVENT_WHENMICROBITGESTURE": "when the gestrue %1",
    "EVENT_WHENFLAGCLICKED": "when %1 clicked",
    "EVENT_WHENTHISSPRITECLICKED": "when this sprite clicked",
    "EVENT_WHENSTAGECLICKED": "when stage clicked",
    "EVENT_WHENTOUCHINGOBJECT": "when this sprite touches %1",
    "EVENT_WHENBROADCASTRECEIVED": "when I receive %1",
    "EVENT_WHENBACKDROPSWITCHESTO": "when backdrop switches to %1",
    "EVENT_WHENGREATERTHAN": "when %1 > %2",
    "EVENT_WHENGREATERTHAN_TIMER": "timer",
    "EVENT_WHENGREATERTHAN_LOUDNESS": "loudness",
    "EVENT_BROADCAST": "broadcast %1",
    "EVENT_BROADCASTANDWAIT": "broadcast %1 and wait",
    "EVENT_WHENKEYPRESSED": "when %1 key pressed",
    "EVENT_WHENMICROBITGESTURE_SHAKEN": "shaken",
    "EVENT_WHENMICROBITGESTURE_TILTEDUPWARD": "tilted upward",
    "EVENT_WHENMICROBITGESTURE_TILTEDDOWNWARD": "tilted downward",
    "EVENT_WHENMICROBITGESTURE_TILTEDDLEFTWARD": "tilted leftward",
    "EVENT_WHENMICROBITGESTURE_TILTEDDRIGHTWARD": "tilted rightward",
    "EVENT_WHENMICROBITGESTURE_FACEUP": "face up",
    "EVENT_WHENMICROBITGESTURE_FACEDOWN": "face down",
    "EVENT_WHENMICROBITGESTURE_FREEFALL": "freefall",
    "EVENT_WHENKEYPRESSED_SPACE": "space",
    "EVENT_WHENKEYPRESSED_LEFT": "left arrow",
    "EVENT_WHENKEYPRESSED_RIGHT": "right arrow",
    "EVENT_WHENKEYPRESSED_DOWN": "down arrow",
    "EVENT_WHENKEYPRESSED_UP": "up arrow",
    "EVENT_WHENKEYPRESSED_ANY": "any",
    "LOOKS_SAYFORSECS": "say %1 for %2 seconds",
    "LOOKS_SAY": "say %1",
    "LOOKS_HELLO": "Hello!",
    "LOOKS_THINKFORSECS": "think %1 for %2 seconds",
    "LOOKS_THINK": "think %1",
    "LOOKS_HMM": "Hmm...",
    "LOOKS_SHOW": "show",
    "LOOKS_HIDE": "hide",
    "LOOKS_HIDEALLSPRITES": "hide all sprites",
    "LOOKS_EFFECT_COLOR": "color",
    "LOOKS_EFFECT_FISHEYE": "fisheye",
    "LOOKS_EFFECT_WHIRL": "whirl",
    "LOOKS_EFFECT_PIXELATE": "pixelate",
    "LOOKS_EFFECT_MOSAIC": "mosaic",
    "LOOKS_EFFECT_BRIGHTNESS": "brightness",
    "LOOKS_EFFECT_GHOST": "ghost",
    "LOOKS_CHANGEEFFECTBY": "change %1 effect by %2",
    "LOOKS_SETEFFECTTO": "set %1 effect to %2",
    "LOOKS_CLEARGRAPHICEFFECTS": "clear graphic effects",
    "LOOKS_CHANGESIZEBY": "change size by %1",
    "LOOKS_SETSIZETO": "set size to %1 %",
    "LOOKS_SIZE": "size",
    "LOOKS_CHANGESTRETCHBY": "change stretch by %1",
    "LOOKS_SETSTRETCHTO": "set stretch to %1 %",
    "LOOKS_SWITCHCOSTUMETO": "switch costume to %1",
    "LOOKS_NEXTCOSTUME": "next costume",
    "LOOKS_SWITCHBACKDROPTO": "switch backdrop to %1",
    "LOOKS_GOTOFRONTBACK": "go to %1 layer",
    "LOOKS_GOTOFRONTBACK_FRONT": "front",
    "LOOKS_GOTOFRONTBACK_BACK": "back",
    "LOOKS_GOFORWARDBACKWARDLAYERS": "go %1 %2 layers",
    "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "forward",
    "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "backward",
    "LOOKS_BACKDROPNUMBERNAME": "backdrop %1",
    "LOOKS_COSTUMENUMBERNAME": "costume %1",
    "LOOKS_NUMBERNAME_NUMBER": "number",
    "LOOKS_NUMBERNAME_NAME": "name",
    "LOOKS_SWITCHBACKDROPTOANDWAIT": "switch backdrop to %1 and wait",
    "LOOKS_NEXTBACKDROP_BLOCK": "next backdrop",
    "LOOKS_NEXTBACKDROP": "next backdrop",
    "LOOKS_PREVIOUSBACKDROP": "previous backdrop",
    "LOOKS_RANDOMBACKDROP": "random backdrop",
    "MOTION_MOVESTEPS": "move %1 steps",
    "MOTION_TURNLEFT": "turn %1 %2 degrees",
    "MOTION_TURNRIGHT": "turn %1 %2 degrees",
    "MOTION_POINTINDIRECTION": "point in direction %1",
    "MOTION_POINTTOWARDS": "point towards %1",
    "MOTION_POINTTOWARDS_POINTER": "mouse-pointer",
    "MOTION_POINTTOWARDS_RANDOM": "random direction",
    "MOTION_GOTO": "go to %1",
    "MOTION_GOTO_POINTER": "mouse-pointer",
    "MOTION_GOTO_RANDOM": "random position",
    "MOTION_GOTOXY": "go to x: %1 y: %2",
    "MOTION_GLIDESECSTOXY": "glide %1 secs to x: %2 y: %3",
    "MOTION_GLIDETO": "glide %1 secs to %2",
    "MOTION_GLIDETO_POINTER": "mouse-pointer",
    "MOTION_GLIDETO_RANDOM": "random position",
    "MOTION_CHANGEXBY": "change x by %1",
    "MOTION_SETX": "set x to %1",
    "MOTION_CHANGEYBY": "change y by %1",
    "MOTION_SETY": "set y to %1",
    "MOTION_IFONEDGEBOUNCE": "if on edge, bounce",
    "MOTION_SETROTATIONSTYLE": "set rotation style %1",
    "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "left-right",
    "MOTION_SETROTATIONSTYLE_DONTROTATE": "don't rotate",
    "MOTION_SETROTATIONSTYLE_ALLAROUND": "all around",
    "MOTION_XPOSITION": "x position",
    "MOTION_YPOSITION": "y position",
    "MOTION_DIRECTION": "direction",
    "MOTION_SCROLLRIGHT": "scroll right %1",
    "MOTION_SCROLLUP": "scroll up %1",
    "MOTION_ALIGNSCENE": "align scene %1",
    "MOTION_ALIGNSCENE_BOTTOMLEFT": "bottom-left",
    "MOTION_ALIGNSCENE_BOTTOMRIGHT": "bottom-right",
    "MOTION_ALIGNSCENE_MIDDLE": "middle",
    "MOTION_ALIGNSCENE_TOPLEFT": "top-left",
    "MOTION_ALIGNSCENE_TOPRIGHT": "top-right",
    "MOTION_XSCROLL": "x scroll",
    "MOTION_YSCROLL": "y scroll",
    "MOTION_STAGE_SELECTED": "Stage selected: no motion blocks",
    "OPERATORS_ADD": "%1 + %2",
    "OPERATORS_SUBTRACT": "%1 - %2",
    "OPERATORS_MULTIPLY": "%1 * %2",
    "OPERATORS_DIVIDE": "%1 / %2",
    "OPERATORS_RANDOM": "pick random %1 to %2",
    "OPERATORS_GT": "%1 > %2",
    "OPERATORS_LT": "%1 < %2",
    "OPERATORS_EQUALS": "%1 = %2",
    "OPERATORS_AND": "%1 and %2",
    "OPERATORS_OR": "%1 or %2",
    "OPERATORS_NOT": "not %1",
    "OPERATORS_JOIN": "join %1 %2",
    "OPERATORS_JOIN_APPLE": "apple",
    "OPERATORS_JOIN_BANANA": "banana",
    "OPERATORS_LETTEROF": "letter %1 of %2",
    "OPERATORS_LETTEROF_APPLE": "a",
    "OPERATORS_LENGTH": "length of %1",
    "OPERATORS_CONTAINS": "%1 contains %2?",
    "OPERATORS_MOD": "%1 mod %2",
    "OPERATORS_ROUND": "round %1",
    "OPERATORS_MATHOP": "%1 of %2",
    "OPERATORS_MATHOP_ABS": "abs",
    "OPERATORS_MATHOP_FLOOR": "floor",
    "OPERATORS_MATHOP_CEILING": "ceiling",
    "OPERATORS_MATHOP_SQRT": "sqrt",
    "OPERATORS_MATHOP_SIN": "sin",
    "OPERATORS_MATHOP_COS": "cos",
    "OPERATORS_MATHOP_TAN": "tan",
    "OPERATORS_MATHOP_ASIN": "asin",
    "OPERATORS_MATHOP_ACOS": "acos",
    "OPERATORS_MATHOP_ATAN": "atan",
    "OPERATORS_MATHOP_LN": "ln",
    "OPERATORS_MATHOP_LOG": "log",
    "OPERATORS_MATHOP_EEXP": "e ^",
    "OPERATORS_MATHOP_10EXP": "10 ^",
    "PROCEDURES_DEFINITION": "define %1",
    "SENSING_TOUCHINGOBJECT": "touching %1?",
    "SENSING_TOUCHINGOBJECT_POINTER": "mouse-pointer",
    "SENSING_TOUCHINGOBJECT_EDGE": "edge",
    "SENSING_TOUCHINGCOLOR": "touching color %1?",
    "SENSING_COLORISTOUCHINGCOLOR": "color %1 is touching %2?",
    "SENSING_DISTANCETO": "distance to %1",
    "SENSING_DISTANCETO_POINTER": "mouse-pointer",
    "SENSING_ASKANDWAIT": "ask %1 and wait",
    "SENSING_ASK_TEXT": "What's your name?",
    "SENSING_ANSWER": "answer",
    "SENSING_KEYPRESSED": "key %1 pressed?",
    "SENSING_MOUSEDOWN": "mouse down?",
    "SENSING_MOUSEX": "mouse x",
    "SENSING_MOUSEY": "mouse y",
    "SENSING_SETDRAGMODE": "set drag mode %1",
    "SENSING_SETDRAGMODE_DRAGGABLE": "draggable",
    "SENSING_SETDRAGMODE_NOTDRAGGABLE": "not draggable",
    "SENSING_LOUDNESS": "loudness",
    "SENSING_LOUD": "loud?",
    "SENSING_TIMER": "timer",
    "SENSING_RESETTIMER": "reset timer",
    "SENSING_OF": "%1 of %2",
    "SENSING_OF_XPOSITION": "x position",
    "SENSING_OF_YPOSITION": "y position",
    "SENSING_OF_DIRECTION": "direction",
    "SENSING_OF_COSTUMENUMBER": "costume #",
    "SENSING_OF_COSTUMENAME": "costume name",
    "SENSING_OF_SIZE": "size",
    "SENSING_OF_VOLUME": "volume",
    "SENSING_OF_BACKDROPNUMBER": "backdrop #",
    "SENSING_OF_BACKDROPNAME": "backdrop name",
    "SENSING_OF_STAGE": "Stage",
    "SENSING_CURRENT": "current %1",
    "SENSING_CURRENT_YEAR": "year",
    "SENSING_CURRENT_MONTH": "month",
    "SENSING_CURRENT_DATE": "date",
    "SENSING_CURRENT_DAYOFWEEK": "day of week",
    "SENSING_CURRENT_HOUR": "hour",
    "SENSING_CURRENT_MINUTE": "minute",
    "SENSING_CURRENT_SECOND": "second",
    "SENSING_DAYSSINCE2000": "days since 2000",
    "SENSING_USERNAME": "username",
    "SENSING_USERID": "user id",
    "SOUND_PLAY": "start sound %1",
    "SOUND_PLAYUNTILDONE": "play sound %1 until done",
    "SOUND_STOPALLSOUNDS": "stop all sounds",
    "SOUND_SETEFFECTO": "set %1 effect to %2",
    "SOUND_CHANGEEFFECTBY": "change %1 effect by %2",
    "SOUND_CLEAREFFECTS": "clear sound effects",
    "SOUND_EFFECTS_PITCH": "pitch",
    "SOUND_EFFECTS_PAN": "pan left/right",
    "SOUND_CHANGEVOLUMEBY": "change volume by %1",
    "SOUND_SETVOLUMETO": "set volume to %1%",
    "SOUND_VOLUME": "volume",
    "SOUND_RECORD": "record...",
    "CATEGORY_MOTION": "Motion",
    "CATEGORY_LOOKS": "Looks",
    "CATEGORY_SOUND": "Sound",
    "CATEGORY_EVENTS": "Events",
    "CATEGORY_CONTROL": "Control",
    "CATEGORY_SENSING": "Sensing",
    "CATEGORY_OPERATORS": "Operators",
    "CATEGORY_VARIABLES": "Variables",
    "CATEGORY_MYBLOCKS": "My Blocks",
    "DUPLICATE": "Duplicate",
    "DELETE": "Delete",
    "ADD_COMMENT": "Add Comment",
    "REMOVE_COMMENT": "Remove Comment",
    "DELETE_BLOCK": "Delete Block",
    "DELETE_X_BLOCKS": "Delete %1 Blocks",
    "DELETE_ALL_BLOCKS": "Delete all %1 blocks?",
    "CLEAN_UP": "Clean up Blocks",
    "HELP": "Help",
    "UNDO": "Undo",
    "REDO": "Redo",
    "EDIT_PROCEDURE": "Edit",
    "SHOW_PROCEDURE_DEFINITION": "Go to definition",
    "WORKSPACE_COMMENT_DEFAULT_TEXT": "Say something...",
    "COLOUR_HUE_LABEL": "Color",
    "COLOUR_SATURATION_LABEL": "Saturation",
    "COLOUR_BRIGHTNESS_LABEL": "Brightness",
    "CHANGE_VALUE_TITLE": "Change value:",
    "RENAME_VARIABLE": "Rename variable",
    "RENAME_VARIABLE_TITLE": "Rename all \"%1\" variables to:",
    "RENAME_VARIABLE_MODAL_TITLE": "Rename Variable",
    "NEW_VARIABLE": "Make a Variable",
    "NEW_VARIABLE_TITLE": "New variable name:",
    "VARIABLE_MODAL_TITLE": "New Variable",
    "VARIABLE_ALREADY_EXISTS": "A variable named \"%1\" already exists.",
    "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "A variable named \"%1\" already exists for another variable of type \"%2\".",
    "DELETE_VARIABLE_CONFIRMATION": "Delete %1 uses of the \"%2\" variable?",
    "CANNOT_DELETE_VARIABLE_PROCEDURE": "Can't delete the variable \"%1\" because it's part of the definition of the function \"%2\"",
    "DELETE_VARIABLE": "Delete the \"%1\" variable",
    "NEW_PROCEDURE": "Make a Block",
    "PROCEDURE_ALREADY_EXISTS": "A procedure named \"%1\" already exists.",
    "PROCEDURE_DEFAULT_NAME": "block name",
    "PROCEDURE_USED": "To delete a block definition, first remove all uses of the block",
    "NEW_LIST": "Make a List",
    "NEW_LIST_TITLE": "New list name:",
    "LIST_MODAL_TITLE": "New List",
    "LIST_ALREADY_EXISTS": "A list named \"%1\" already exists.",
    "RENAME_LIST_TITLE": "Rename all \"%1\" lists to:",
    "RENAME_LIST_MODAL_TITLE": "Rename List",
    "DEFAULT_LIST_ITEM": "thing",
    "DELETE_LIST": "Delete the \"%1\" list",
    "RENAME_LIST": "Rename list",
    "NEW_BROADCAST_MESSAGE": "New message",
    "NEW_BROADCAST_MESSAGE_TITLE": "New message name:",
    "BROADCAST_MODAL_TITLE": "New Message",
    "DEFAULT_BROADCAST_MESSAGE_NAME": "message1"
};

Blockly.ScratchMsgs.locales["ko"] =
    {
        "CONTROL_FOREVER": "무한 반복하기",
        "CONTROL_REPEAT": "%1 번 반복하기",
        "CONTROL_IF": "만약 %1 (이)라면",
        "CONTROL_ELSE": "아니면",
        "CONTROL_STOP": "멈추기",
        "CONTROL_STOP_ALL": "모두",
        "CONTROL_STOP_THIS": "이 스크립트",
        "CONTROL_STOP_OTHER": "이 스프라이트에 있는 다른 스크립트",
        "CONTROL_WAIT": "%1 초 기다리기",
        "CONTROL_WAITUNTIL": "%1 까지 기다리기",
        "CONTROL_REPEATUNTIL": "%1 까지 반복하기",
        "CONTROL_WHILE": "%1 동안 반복하기",
        "CONTROL_FOREACH": "%1 변수로 %2 번 반복하기",
        "CONTROL_STARTASCLONE": "복제되었을 때",
        "CONTROL_CREATECLONEOF": "%1 복제하기",
        "CONTROL_CREATECLONEOF_MYSELF": "나 자신",
        "CONTROL_DELETETHISCLONE": "이 복제본 삭제하기",
        "CONTROL_COUNTER": "카운터",
        "CONTROL_INCRCOUNTER": "카운터 증가하기",
        "CONTROL_CLEARCOUNTER": "카운터 초기화",
        "CONTROL_ALLATONCE": "한 번에 실행하기",
        "DATA_SETVARIABLETO": "%1 을(를) %2 로 정하기",
        "DATA_CHANGEVARIABLEBY": "%1 을(를) %2 만큼 바꾸기",
        "DATA_SHOWVARIABLE": "%1 변수 보이기",
        "DATA_HIDEVARIABLE": "%1 변수 숨기기",
        "DATA_ADDTOLIST": "%1 을(를) %2 에 추가하기",
        "DATA_DELETEOFLIST": "%1 번째 항목을 %2 에서 삭제하기",
        "DATA_DELETEALLOFLIST": "%1 의 항목을 모두 삭제하기 ",
        "DATA_INSERTATLIST": "%1 을(를) %3 리스트의 %2 번째에 넣기",
        "DATA_REPLACEITEMOFLIST": "%2 리스트의 %1 번째 항목을 %3 으로 바꾸기",
        "DATA_ITEMOFLIST": "%2 리스트의 %1 번째 항목",
        "DATA_ITEMNUMOFLIST": "%2 리스트에서 %1 항목의 위치",
        "DATA_LENGTHOFLIST": "%1 의 길이",
        "DATA_LISTCONTAINSITEM": "%1 이(가) %2 을(를) 포함하는가?",
        "DATA_SHOWLIST": "%1 리스트 보이기",
        "DATA_HIDELIST": "%1 리스트 숨기기",
        "DATA_INDEX_ALL": "모두",
        "DATA_INDEX_LAST": "마지막",
        "DATA_INDEX_RANDOM": "랜덤",
        "EVENT_WHENFLAGCLICKED": "%1 클릭했을 때",
        "EVENT_WHENTHISSPRITECLICKED": "이 스프라이트를 클릭했을 때",
        "EVENT_WHENSTAGECLICKED": "무대를 클릭했을 때",
        "EVENT_WHENTOUCHINGOBJECT": "이 스프라이트가 %1 에 닿았을 때",
        "EVENT_WHENBROADCASTRECEIVED": "%1 신호를 받았을 때",
        "EVENT_WHENBACKDROPSWITCHESTO": "배경이 %1 (으)로 바뀌었을 때",
        "EVENT_WHENGREATERTHAN": "%1 > %2 일 때",
        "EVENT_WHENGREATERTHAN_TIMER": "타이머",
        "EVENT_WHENGREATERTHAN_LOUDNESS": "음량",
        "EVENT_BROADCAST": "%1 신호 보내기",
        "EVENT_BROADCASTANDWAIT": "%1 신호 보내고 기다리기",
        "EVENT_WHENKEYPRESSED": "%1 키를 눌렀을 때",
        "EVENT_WHENKEYPRESSED_SPACE": "스페이스",
        "EVENT_WHENKEYPRESSED_LEFT": "왼쪽 화살표",
        "EVENT_WHENKEYPRESSED_RIGHT": "오른쪽 화살표",
        "EVENT_WHENKEYPRESSED_DOWN": "아래쪽 화살표",
        "EVENT_WHENKEYPRESSED_UP": "위쪽 화살표",
        "EVENT_WHENKEYPRESSED_ANY": "아무",
        "LOOKS_SAYFORSECS": "%1 을(를) %2 초 동안 말하기",
        "LOOKS_SAY": "%1 말하기",
        "LOOKS_HELLO": "안녕!",
        "LOOKS_THINKFORSECS": "%1 을(를) %2 초 동안 생각하기",
        "LOOKS_THINK": "%1 생각하기",
        "LOOKS_HMM": "음...",
        "LOOKS_SHOW": "보이기",
        "LOOKS_HIDE": "숨기기",
        "LOOKS_HIDEALLSPRITES": "모든 스프라이트 숨기기",
        "LOOKS_EFFECT_COLOR": "색깔",
        "LOOKS_EFFECT_FISHEYE": "어안 렌즈",
        "LOOKS_EFFECT_WHIRL": "소용돌이",
        "LOOKS_EFFECT_PIXELATE": "픽셀화",
        "LOOKS_EFFECT_MOSAIC": "모자이크",
        "LOOKS_EFFECT_BRIGHTNESS": "밝기",
        "LOOKS_EFFECT_GHOST": "투명도",
        "LOOKS_CHANGEEFFECTBY": "%1 효과를 %2 만큼 바꾸기",
        "LOOKS_SETEFFECTTO": "%1 효과를 %2 (으)로 정하기",
        "LOOKS_CLEARGRAPHICEFFECTS": "그래픽 효과 지우기",
        "LOOKS_CHANGESIZEBY": "크기를 %1 만큼 바꾸기",
        "LOOKS_SETSIZETO": "크기를 %1 %로 정하기",
        "LOOKS_SIZE": "크기",
        "LOOKS_CHANGESTRETCHBY": "너비를 %1 만큼 바꾸기",
        "LOOKS_SETSTRETCHTO": "너비를 %1 %로 정하기",
        "LOOKS_SWITCHCOSTUMETO": "모양을 %1 (으)로 바꾸기",
        "LOOKS_NEXTCOSTUME": "다음 모양으로 바꾸기",
        "LOOKS_SWITCHBACKDROPTO": "배경을 %1 (으)로 바꾸기",
        "LOOKS_GOTOFRONTBACK": "%1 으로 순서 바꾸기",
        "LOOKS_GOTOFRONTBACK_FRONT": "맨 앞쪽",
        "LOOKS_GOTOFRONTBACK_BACK": "맨 뒤쪽",
        "LOOKS_GOFORWARDBACKWARDLAYERS": "%1 %2 단계 보내기",
        "LOOKS_GOFORWARDBACKWARDLAYERS_FORWARD": "앞으로",
        "LOOKS_GOFORWARDBACKWARDLAYERS_BACKWARD": "뒤로",
        "LOOKS_BACKDROPNUMBERNAME": "배경 %1",
        "LOOKS_COSTUMENUMBERNAME": "모양 %1",
        "LOOKS_NUMBERNAME_NUMBER": "번호",
        "LOOKS_NUMBERNAME_NAME": "이름",
        "LOOKS_SWITCHBACKDROPTOANDWAIT": "배경을 %1 (으)로 바꾸고 기다리기",
        "LOOKS_NEXTBACKDROP_BLOCK": "다음 배경으로 바꾸기",
        "LOOKS_NEXTBACKDROP": "다음 배경",
        "LOOKS_PREVIOUSBACKDROP": "이전 배경",
        "LOOKS_RANDOMBACKDROP": "랜덤 배경",
        "MOTION_MOVESTEPS": "%1 만큼 움직이기",
        "MOTION_TURNLEFT": "%1 방향으로 %2 도 회전하기",
        "MOTION_TURNRIGHT": "%1 방향으로 %2 도 돌기",
        "MOTION_POINTINDIRECTION": "%1 도 방향 보기",
        "MOTION_POINTTOWARDS": "%1 쪽 보기",
        "MOTION_POINTTOWARDS_POINTER": "마우스 포인터",
        "MOTION_POINTTOWARDS_RANDOM": "랜덤 방향",
        "MOTION_GOTO": "%1 (으)로 이동하기",
        "MOTION_GOTO_POINTER": "마우스 포인터",
        "MOTION_GOTO_RANDOM": "무작위 위치",
        "MOTION_GOTOXY": "x: %1 y: %2 (으)로 이동하기",
        "MOTION_GLIDESECSTOXY": "%1 초 동안 x: %2 y: %3 (으)로 이동하기",
        "MOTION_GLIDETO": "%1 초 동안 %2 (으)로 이동하기",
        "MOTION_GLIDETO_POINTER": "마우스 포인터",
        "MOTION_GLIDETO_RANDOM": "랜덤 위치",
        "MOTION_CHANGEXBY": "x좌표를 %1 만큼 바꾸기",
        "MOTION_SETX": "x좌표를 %1 (으)로 정하기",
        "MOTION_CHANGEYBY": "y좌표를 %1 만큼 바꾸기",
        "MOTION_SETY": "y좌표를 %1 (으)로 정하기",
        "MOTION_IFONEDGEBOUNCE": "벽에 닿으면 튕기기",
        "MOTION_SETROTATIONSTYLE": "회전 방식을 %1 (으)로 정하기",
        "MOTION_SETROTATIONSTYLE_LEFTRIGHT": "왼쪽-오른쪽",
        "MOTION_SETROTATIONSTYLE_DONTROTATE": "회전하지 않기",
        "MOTION_SETROTATIONSTYLE_ALLAROUND": "회전하기",
        "MOTION_XPOSITION": "x좌표",
        "MOTION_YPOSITION": "y좌표",
        "MOTION_DIRECTION": "방향",
        "MOTION_SCROLLRIGHT": "오른쪽으로 %1 만큼 스크롤하기",
        "MOTION_SCROLLUP": "위쪽으로 %1 만큼 스크롤하기",
        "MOTION_ALIGNSCENE": "화면을 %1 로 정렬하기",
        "MOTION_ALIGNSCENE_BOTTOMLEFT": "왼쪽 아래",
        "MOTION_ALIGNSCENE_BOTTOMRIGHT": "오른쪽 아래",
        "MOTION_ALIGNSCENE_MIDDLE": "가운데",
        "MOTION_ALIGNSCENE_TOPLEFT": "왼쪽 위",
        "MOTION_ALIGNSCENE_TOPRIGHT": "오른쪽 위",
        "MOTION_XSCROLL": "x 스크롤",
        "MOTION_YSCROLL": "y 스크롤",
        "MOTION_STAGE_SELECTED": "무대 선택됨: 동작 블록 없음",
        "OPERATORS_ADD": "%1 + %2",
        "OPERATORS_SUBTRACT": "%1 - %2",
        "OPERATORS_MULTIPLY": "%1 * %2",
        "OPERATORS_DIVIDE": "%1 / %2",
        "OPERATORS_RANDOM": "%1 부터 %2 사이의 난수",
        "OPERATORS_GT": "%1 > %2",
        "OPERATORS_LT": "%1 < %2",
        "OPERATORS_EQUALS": "%1 = %2",
        "OPERATORS_AND": "%1 그리고 %2",
        "OPERATORS_OR": "%1 또는 %2",
        "OPERATORS_NOT": "%1 이(가) 아니다",
        "OPERATORS_JOIN": "%1 와(과) %2 결합하기",
        "OPERATORS_JOIN_APPLE": "가위",
        "OPERATORS_JOIN_BANANA": "나무",
        "OPERATORS_LETTEROF": "%2 의 %1 번째 글자",
        "OPERATORS_LETTEROF_APPLE": "가",
        "OPERATORS_LENGTH": "%1 의 길이",
        "OPERATORS_CONTAINS": "%1 이(가) %2 을(를) 포함하는가?",
        "OPERATORS_MOD": "%1 나누기 %2 의 나머지",
        "OPERATORS_ROUND": "%1 의 반올림",
        "OPERATORS_MATHOP": "%1 ( %2 )",
        "OPERATORS_MATHOP_ABS": "절댓값",
        "OPERATORS_MATHOP_FLOOR": "버림",
        "OPERATORS_MATHOP_CEILING": "올림",
        "OPERATORS_MATHOP_SQRT": "제곱근",
        "OPERATORS_MATHOP_SIN": "sin",
        "OPERATORS_MATHOP_COS": "cos",
        "OPERATORS_MATHOP_TAN": "tan",
        "OPERATORS_MATHOP_ASIN": "asin",
        "OPERATORS_MATHOP_ACOS": "acos",
        "OPERATORS_MATHOP_ATAN": "atan",
        "OPERATORS_MATHOP_LN": "ln",
        "OPERATORS_MATHOP_LOG": "log",
        "OPERATORS_MATHOP_EEXP": "e ^",
        "OPERATORS_MATHOP_10EXP": "10 ^",
        "PROCEDURES_DEFINITION": "%1 정의하기",
        "SENSING_TOUCHINGOBJECT": "%1 에 닿았는가?",
        "SENSING_TOUCHINGOBJECT_POINTER": "마우스 포인터",
        "SENSING_TOUCHINGOBJECT_EDGE": "벽",
        "SENSING_TOUCHINGCOLOR": "%1 색에 닿았는가?",
        "SENSING_COLORISTOUCHINGCOLOR": "%1 색이 %2 색에 닿았는가?",
        "SENSING_DISTANCETO": "%1 까지의 거리",
        "SENSING_DISTANCETO_POINTER": "마우스 포인터",
        "SENSING_ASKANDWAIT": "%1 라고 묻고 기다리기",
        "SENSING_ASK_TEXT": "너 이름이 뭐니?",
        "SENSING_ANSWER": "대답",
        "SENSING_KEYPRESSED": "%1 키를 눌렸는가?",
        "SENSING_MOUSEDOWN": "마우스를 클릭했는가?",
        "SENSING_MOUSEX": "마우스의 x좌표",
        "SENSING_MOUSEY": "마우스의 y좌표",
        "SENSING_SETDRAGMODE": "드래그 모드를 %1 상태로 정하기",
        "SENSING_SETDRAGMODE_DRAGGABLE": "드래그 할 수 있는",
        "SENSING_SETDRAGMODE_NOTDRAGGABLE": "드래그 할 수 없는",
        "SENSING_LOUDNESS": "음량",
        "SENSING_LOUD": "소리가 큰가?",
        "SENSING_TIMER": "타이머",
        "SENSING_RESETTIMER": "타이머 초기화",
        "SENSING_OF": "%2 의 %1",
        "SENSING_OF_XPOSITION": "x좌표",
        "SENSING_OF_YPOSITION": "y좌표",
        "SENSING_OF_DIRECTION": "방향",
        "SENSING_OF_COSTUMENUMBER": "모양 번호",
        "SENSING_OF_COSTUMENAME": "모양 이름",
        "SENSING_OF_SIZE": "크기",
        "SENSING_OF_VOLUME": "음량",
        "SENSING_OF_BACKDROPNUMBER": "배경 번호",
        "SENSING_OF_BACKDROPNAME": "배경 이름",
        "SENSING_OF_STAGE": "무대",
        "SENSING_CURRENT": "현재 %1",
        "SENSING_CURRENT_YEAR": "년",
        "SENSING_CURRENT_MONTH": "월",
        "SENSING_CURRENT_DATE": "일",
        "SENSING_CURRENT_DAYOFWEEK": "요일",
        "SENSING_CURRENT_HOUR": "시",
        "SENSING_CURRENT_MINUTE": "분",
        "SENSING_CURRENT_SECOND": "초",
        "SENSING_DAYSSINCE2000": "2000년 이후 현재까지 날짜 수",
        "SENSING_USERNAME": "사용자 이름",
        "SENSING_USERID": "사용자 번호",
        "SOUND_PLAY": "%1 재생하기",
        "SOUND_PLAYUNTILDONE": "%1 끝까지 재생하기",
        "SOUND_STOPALLSOUNDS": "모든 소리 끄기",
        "SOUND_SETEFFECTO": "%1 효과를 %2 로 정하기",
        "SOUND_CHANGEEFFECTBY": "%1 효과를 %2 만큼 바꾸기",
        "SOUND_CLEAREFFECTS": "소리 효과 지우기",
        "SOUND_EFFECTS_PITCH": "음 높이",
        "SOUND_EFFECTS_PAN": "음향 위치 왼쪽/오른쪽",
        "SOUND_CHANGEVOLUMEBY": "음량을 %1 만큼 바꾸기",
        "SOUND_SETVOLUMETO": "음량을 %1%로 정하기",
        "SOUND_VOLUME": "음량",
        "SOUND_RECORD": "녹음하기...",
        "CATEGORY_MOTION": "동작",
        "CATEGORY_LOOKS": "형태",
        "CATEGORY_SOUND": "소리",
        "CATEGORY_EVENTS": "이벤트",
        "CATEGORY_CONTROL": "제어",
        "CATEGORY_SENSING": "감지",
        "CATEGORY_OPERATORS": "연산",
        "CATEGORY_VARIABLES": "변수",
        "CATEGORY_MYBLOCKS": "내 블록",
        "DUPLICATE": "복사하기",
        "DELETE": "삭제하기",
        "ADD_COMMENT": "주석 넣기",
        "REMOVE_COMMENT": "주석 지우기",
        "DELETE_BLOCK": "블록 삭제하기",
        "DELETE_X_BLOCKS": "블록 %1개 삭제하기",
        "DELETE_ALL_BLOCKS": "%1개의 블록을 모두 삭제할까요?",
        "CLEAN_UP": "블록 정리하기",
        "HELP": "도움말",
        "UNDO": "실행 취소",
        "REDO": "다시 실행",
        "EDIT_PROCEDURE": "편집",
        "SHOW_PROCEDURE_DEFINITION": "정의로 이동하기",
        "WORKSPACE_COMMENT_DEFAULT_TEXT": "무엇이든 말하여 봅시다.",
        "COLOUR_HUE_LABEL": "색상",
        "COLOUR_SATURATION_LABEL": "채도",
        "COLOUR_BRIGHTNESS_LABEL": "명도",
        "CHANGE_VALUE_TITLE": "값 바꾸기:",
        "RENAME_VARIABLE": "변수 이름 바꾸기",
        "RENAME_VARIABLE_TITLE": "\"%1\" 변수를 모두 다음으로 이름 바꾸기:",
        "RENAME_VARIABLE_MODAL_TITLE": "변수 이름 바꾸기",
        "NEW_VARIABLE": "변수 만들기",
        "NEW_VARIABLE_TITLE": "새로운 변수 이름:",
        "VARIABLE_MODAL_TITLE": "새로운 변수",
        "VARIABLE_ALREADY_EXISTS": "이름이 \"%1\"인 변수는 이미 존재합니다.",
        "VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE": "이름이 \"%1\"인 변수는 이미 \"%2\" 형태의 다른 변수로 존재합니다.",
        "DELETE_VARIABLE_CONFIRMATION": "\"%2\" 변수가 사용된 %1곳을 삭제할까요?",
        "CANNOT_DELETE_VARIABLE_PROCEDURE": "\"%2\" 함수의 정의 중 일부분이기 때문에 \"%1\" 변수를 삭제할 수 없습니다.",
        "DELETE_VARIABLE": "\"%1\" 변수 삭제하기",
        "NEW_PROCEDURE": "블록 만들기",
        "PROCEDURE_ALREADY_EXISTS": "이름이 \"%1\"인 함수는 이미 존재합니다.",
        "PROCEDURE_DEFAULT_NAME": "블록 이름",
        "PROCEDURE_USED": "To delete a block definition, first remove all uses of the block",
        "NEW_LIST": "리스트 만들기",
        "NEW_LIST_TITLE": "새로운 리스트 이름:",
        "LIST_MODAL_TITLE": "새로운 리스트",
        "LIST_ALREADY_EXISTS": "이름이 \"%1\"인 리스트는 이미 존재합니다.",
        "RENAME_LIST_TITLE": "\"%1\" 리스트를 모두 다음으로 이름 바꾸기:",
        "RENAME_LIST_MODAL_TITLE": "리스트 이름 바꾸기",
        "DEFAULT_LIST_ITEM": "항목",
        "DELETE_LIST": "\"%1\" 리스트 삭제하기",
        "RENAME_LIST": "리스트 이름 바꾸기",
        "NEW_BROADCAST_MESSAGE": "새로운 메시지",
        "NEW_BROADCAST_MESSAGE_TITLE": "새로운 메시지 이름:",
        "BROADCAST_MODAL_TITLE": "새로운 메시지",
        "DEFAULT_BROADCAST_MESSAGE_NAME": "메시지1"
    };
// End of combined translations
