# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: 
      - main
    
jobs:
  release:
    strategy:
      matrix:
        node-version: [14.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "2.x"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          
      - run: npm install
      - run: npm run prepublish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          owner: ottawastem
          repo: scratch-arduino
          event_type: release_scratch_arduino_blocks
          token: ${{ secrets.TOKEN_GITHUB_SECRET }}